-- AlterTable
ALTER TABLE `autoecole` ADD COLUMN `date_creation` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `cars` ADD COLUMN `date_creation` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `condidat` ADD COLUMN `date_creation` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `gerantecole` ADD COLUMN `date_creation` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `moniteur` ADD COLUMN `date_creation` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `user` ADD COLUMN `date_creation` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0);
