-- CreateTable
CREATE TABLE `contrat` (
    `idContrat` INTEGER NOT NULL AUTO_INCREMENT,
    `idAutoEcole` INTEGER NOT NULL,
    `idPermi` INTEGER NOT NULL,
    `statut` VARCHAR(254) NOT NULL,
    `date_creation` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `FK_CONTRAT_AUTOECOLE`(`idAutoEcole`),
    INDEX `FK_CONTRAT_PERMI`(`idPermi`),
    PRIMARY KEY (`idContrat`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `contrat` ADD CONSTRAINT `FK_CONTRAT_AUTOECOLE` FOREIGN KEY (`idAutoEcole`) REFERENCES `autoecole`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `contrat` ADD CONSTRAINT `FK_CONTRAT_PERMI` FOREIGN KEY (`idPermi`) REFERENCES `permi`(`idPermi`) ON DELETE RESTRICT ON UPDATE RESTRICT;
