-- DropForeignKey
ALTER TABLE `calendrier` DROP FOREIGN KEY `fk_calendrier_autoecole`;

-- DropForeignKey
ALTER TABLE `calendrier` DROP FOREIGN KEY `FK_notification`;

-- DropForeignKey
ALTER TABLE `cars` DROP FOREIGN KEY `fk_idAutoEcole_cars`;

-- DropForeignKey
ALTER TABLE `condidat` DROP FOREIGN KEY `condidat_ibfk_1`;

-- DropForeignKey
ALTER TABLE `demande` DROP FOREIGN KEY `fk_demande_autoecole`;

-- DropForeignKey
ALTER TABLE `demande` DROP FOREIGN KEY `demande_ibfk_1`;

-- DropForeignKey
ALTER TABLE `demande` DROP FOREIGN KEY `fk_demande_notification`;

-- DropForeignKey
ALTER TABLE `demande` DROP FOREIGN KEY `demande_ibfk_2`;

-- DropForeignKey
ALTER TABLE `moniteur` DROP FOREIGN KEY `moniteur_ibfk_1`;

-- DropForeignKey
ALTER TABLE `tarification` DROP FOREIGN KEY `tarification_ibfk_2`;

-- DropForeignKey
ALTER TABLE `tarification` DROP FOREIGN KEY `tarification_ibfk_1`;

-- DropForeignKey
ALTER TABLE `user` DROP FOREIGN KEY `user_ibfk_1`;

-- CreateIndex
CREATE INDEX `FK_PERMI_PRISE_CONDIDAT` ON `permi`(`idUser`);

-- CreateIndex
CREATE INDEX `FK_PERMISFO_PERMISFOU_PERMI` ON `permisfournis`(`idPermi`);

-- AddForeignKey
ALTER TABLE `calendrier` ADD CONSTRAINT `FK_EVENEMEN_ORGANISER_AUTOECOL` FOREIGN KEY (`idAutoEcole`) REFERENCES `autoecole`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `calendrier` ADD CONSTRAINT `FK_EVENEMEN_PARTICIPA_VOITURE` FOREIGN KEY (`idVoiture`) REFERENCES `cars`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `calendrier` ADD CONSTRAINT `FK_EVENEMEN_LIEE_NOTIFICA` FOREIGN KEY (`idNotification`) REFERENCES `notification`(`idNotification`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `calendrier` ADD CONSTRAINT `FK_EVENEMEN_PARTICIPE_CONDIDAT` FOREIGN KEY (`idUser`) REFERENCES `condidat`(`idCondidat`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `cars` ADD CONSTRAINT `FK_VOITURE_UTILISER_AUTOECOL` FOREIGN KEY (`idAutoEcole`) REFERENCES `autoecole`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `cars` ADD CONSTRAINT `FK_VOITURE_ETRE_COND_MONITEUR` FOREIGN KEY (`idUser`) REFERENCES `moniteur`(`idMoniteur`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `cars` ADD CONSTRAINT `FK_VOITURE_ETRE_COND_GERANTEC` FOREIGN KEY (`Ger_idUser`) REFERENCES `gerantecole`(`idGerant`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `demande` ADD CONSTRAINT `FK_DEMANDE_PASSER_AUTOECOL` FOREIGN KEY (`idAutoecole`) REFERENCES `autoecole`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `demande` ADD CONSTRAINT `FK_DEMANDE_CONCERNER_FORFAIT` FOREIGN KEY (`idForfait`) REFERENCES `forfait`(`idForfait`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `demande` ADD CONSTRAINT `FK_DEMANDE_LIEE_NOTIFICA` FOREIGN KEY (`idNotification`) REFERENCES `notification`(`idNotification`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `demande` ADD CONSTRAINT `FK_DEMANDE_ENVOYER_USER` FOREIGN KEY (`idUser`) REFERENCES `user`(`idUser`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `user` ADD CONSTRAINT `FK_USER_ROLE_ROLES` FOREIGN KEY (`idRole`) REFERENCES `roles`(`idRole`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `tarification` ADD CONSTRAINT `FK_TARIFICA_BENEFICIE_USER` FOREIGN KEY (`idUser`) REFERENCES `user`(`idUser`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `tarification` ADD CONSTRAINT `FK_TARIFICA_BENEFICIE_SERVICE` FOREIGN KEY (`idService`) REFERENCES `service`(`idService`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `tarification` ADD CONSTRAINT `FK_TARIFICA_CREER_PAT_GERANTEC` FOREIGN KEY (`Ger_idUser`) REFERENCES `gerantecole`(`idGerant`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `moniteur` ADD CONSTRAINT `FK_MONITEUR_EMPLOYEME_AUTOECOL` FOREIGN KEY (`idAutoecole`) REFERENCES `autoecole`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `moniteur` ADD CONSTRAINT `FK_MONITEUR_GENERALIS_USER` FOREIGN KEY (`idMoniteur`) REFERENCES `user`(`idUser`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `condidat` ADD CONSTRAINT `FK_CONDIDAT_INSCRIPTI_AUTOECOL` FOREIGN KEY (`idAutoecole`) REFERENCES `autoecole`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `condidat` ADD CONSTRAINT `FK_CONDIDAT_GENERALIS_USER` FOREIGN KEY (`idCondidat`) REFERENCES `user`(`idUser`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `permi` ADD CONSTRAINT `FK_PERMI_PRISE_CONDIDAT` FOREIGN KEY (`idUser`) REFERENCES `condidat`(`idCondidat`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `permisfournis` ADD CONSTRAINT `FK_PERMISFO_PERMISFOU_AUTOECOL` FOREIGN KEY (`idAutoecole`) REFERENCES `autoecole`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `permisfournis` ADD CONSTRAINT `FK_PERMISFO_PERMISFOU_PERMI` FOREIGN KEY (`idPermi`) REFERENCES `permi`(`idPermi`) ON DELETE RESTRICT ON UPDATE RESTRICT;
